### ISSUE TITLE
Uploading heavy files to gdrive fails with httplib2.error.RedirectMissingLocation raised by googleapiclient

### ISSUE THREAD

**Issue by annapods** [annapods/podfic_poster#1]
When trying to upload a heavy file (112Mo) to google drive, process freezes for a while then throws the following error:

``` shell
Uploading podfic files to gdrive...
../../../Musique/2.5 to post/ow - mdlv/[OW] Mémoire de la Veuve.mp3
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    gdrive_uploader.upload_audio()
  File "/home/pod/Documents/code/html generator/gdrive_uploader.py", line 52, in upload_audio
    self.upload_file(path)
  File "/home/pod/Documents/code/html generator/gdrive_uploader.py", line 79, in upload_file
    file.Upload()
  File "/home/pod/Documents/code/html generator/.venv/lib/python3.7/site-packages/pydrive/files.py", line 285, in Upload
    self._FilesInsert(param=param)
  File "/home/pod/Documents/code/html generator/.venv/lib/python3.7/site-packages/pydrive/auth.py", line 75, in _decorated
    return decoratee(self, *args, **kwargs)
  File "/home/pod/Documents/code/html generator/.venv/lib/python3.7/site-packages/pydrive/files.py", line 369, in _FilesInsert
    http=self.http)
  File "/home/pod/Documents/code/html generator/.venv/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/pod/Documents/code/html generator/.venv/lib/python3.7/site-packages/googleapiclient/http.py", line 901, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/home/pod/Documents/code/html generator/.venv/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/pod/Documents/code/html generator/.venv/lib/python3.7/site-packages/googleapiclient/http.py", line 1084, in next_chunk
    self.resumable_uri, method="PUT", body=data, headers=headers
  File "/home/pod/Documents/code/html generator/.venv/lib/python3.7/site-packages/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/home/pod/Documents/code/html generator/.venv/lib/python3.7/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/home/pod/Documents/code/html generator/.venv/lib/python3.7/site-packages/httplib2/__init__.py", line 1702, in request
    conn, authority, uri, request_uri, method, body, headers, redirections, cachekey,
  File "/home/pod/Documents/code/html generator/.venv/lib/python3.7/site-packages/httplib2/__init__.py", line 1445, in _request
    _("Redirected but the response is missing a Location: header."), response, content,
httplib2.error.RedirectMissingLocation: Redirected but the response is missing a Location: header.
```

First reference to a similar issue: #https://github.com/googlearchive/PyDrive/issues/27
A potential fix by pinning the versions of the underlying APIs (didn't work): #https://github.com/googleapis/google-api-python-client/issues/803
2021 deprecation notice for pydrive: #https://github.com/googlearchive/PyDrive/commit/42022f9a1c48f435438fce74ad4032ec9f34cfd1

Proposed solution: switch to [pydrive2](https://github.com/iterative/PyDrive2), which is actively maintained.

**Comment by annapods** [comment]
Fixed, see #https://github.com/annapods/podfic_poster/commit/a9a32f39d9000072ec6dee0f904bc7bb7f332dcc
